name: Run Portfolio Website Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install -g @lhci/cli

    - name: Run Lighthouse CI (Performance & SEO Tests)
      run: |
        lhci autorun --collect.staticDistDir=./ # Adjust path if needed

    - name: Upload Lighthouse Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: lighthouse-report
        path: .lighthouseci
